import path from 'path';
import fs from 'fs';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const archiver = require('archiver') as (format: string, opts?: object) => import('archiver').Archiver;
import { ArchitectureVersion } from '../models/architecture-version.model';

import logger from '../utils/logger';

// Simple regex-based Terraform lint validator
function lintTerraform(code: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!code.includes('terraform {')) errors.push('Missing terraform {} block');
  if (!code.includes('provider "aws"') && !code.includes('provider "google"') && !code.includes('provider "azurerm"'))
    errors.push('No cloud provider block found');
  if ((code.match(/resource "/g) || []).length === 0) errors.push('No resource blocks found');

  const openBraces = (code.match(/{/g) || []).length;
  const closeBraces = (code.match(/}/g) || []).length;
  if (openBraces !== closeBraces) errors.push(`Brace mismatch: ${openBraces} open, ${closeBraces} close`);

  return { valid: errors.length === 0, errors };
}

export const terraformService = {
  async getTerraformCode(projectId: string): Promise<{ code: string; versionId: string } | null> {
    const version = await ArchitectureVersion.findOne({
      where: { projectId, isCurrent: true },
    });
    if (!version || !version.terraformCode) return null;
    return { code: version.terraformCode, versionId: version.id };
  },

  async downloadTerraformZip(projectId: string): Promise<Buffer> {
    const result = await this.getTerraformCode(projectId);
    if (!result) throw Object.assign(new Error('No Terraform code available'), { status: 404 });

    const tmpDir = path.join(process.cwd(), 'tmp');
    if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir, { recursive: true });

    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const archive = archiver('zip', { zlib: { level: 9 } });

      archive.on('data', (chunk: Buffer) => chunks.push(chunk));
      archive.on('end', () => resolve(Buffer.concat(chunks)));
      archive.on('error', reject);

      archive.append(result.code, { name: 'main.tf' });
      archive.append(
        `# Terraform Variables\nvariable "db_password" {\n  type      = string\n  sensitive = true\n}\n`,
        { name: 'variables.tf' }
      );
      archive.append(
        `# Terraform Outputs\n# See main.tf for output definitions\n`,
        { name: 'outputs.tf' }
      );
      archive.append(
        `# Generated by AI Architecture Agent\n# Review and customize before applying.\n# Run: terraform init && terraform plan\n`,
        { name: 'README.md' }
      );

      archive.finalize();
    });
  },

  async validateTerraform(projectId: string): Promise<{ valid: boolean; errors: string[]; warnings: string[] }> {
    const result = await this.getTerraformCode(projectId);
    if (!result) throw Object.assign(new Error('No Terraform code available'), { status: 404 });

    const lint = lintTerraform(result.code);
    const warnings: string[] = [];

    // Additional warnings
    if (!result.code.includes('deletion_protection')) warnings.push('Consider enabling deletion_protection on databases');
    if (!result.code.includes('multi_az')) warnings.push('Consider enabling multi_az for production databases');
    if (!result.code.includes('backend "s3"')) warnings.push('Consider using a remote backend for state management');

    logger.info(`Terraform validation for project ${projectId}: valid=${lint.valid}`);
    return { ...lint, warnings };
  },

  async getCloudMapping(projectId: string): Promise<object | null> {
    const version = await ArchitectureVersion.findOne({ where: { projectId, isCurrent: true } });
    return version?.cloudMapping || null;
  },
};
