# agents/src/terraform/terraform_agent.py

import json
from src.common.base_agent import BaseAgent
from src.common.context import AgentContext

class TerraformAgent(BaseAgent):
    def __init__(self):
        super().__init__("Terraform Agent")

    def run(self, context: AgentContext) -> AgentContext:
        self.log_start(context, f"Compiling Terraform Infrastructure-as-Code for {context.cloud_provider.upper()}...")

        if not context.cloud_mappings:
            self.log_failure(context, "No cloud service mappings found in workspace context to generate Terraform for.")
            raise ValueError("cloud_mappings list is empty.")

        # Prepare context details for the prompt
        mappings_str = "\n".join([
            f"- Component [{m.component_id}]: {m.service_name} (Tier: {m.tier}, Region: {m.region})"
            for m in context.cloud_mappings
        ])

        system_prompt = (
            f"You are an expert DevOps Engineer specializing in {context.cloud_provider.upper()} and Terraform.\n"
            "Your task is to generate complete, valid, and deployable Terraform configuration code "
            "based on the provided cloud service mappings.\n\n"
            "Format the output as a JSON object matching this schema:\n"
            "{\n"
            "  'files': {\n"
            "    'main.tf': '...terraform code contents...' (string),\n"
            "    'variables.tf': '...terraform code contents...' (string),\n"
            "    'outputs.tf': '...terraform code contents...' (string)\n"
            "  }\n"
            "}\n\n"
            "Guidelines:\n"
            "1. Output clean, modular Terraform files that define the provider, resources, variables, and outputs.\n"
            "2. Ensure variables match standard configurations and outputs export endpoints (like DB endpoint, Load Balancer URL).\n"
            "3. Enforce best practices (e.g., secure VPC setups, private database subnets).\n"
            "4. Output ONLY a valid JSON object. Do not include conversational text or Markdown formatting blocks."
        )

        user_prompt = (
            f"Service Mappings to generate Infrastructure for:\n{mappings_str}\n"
        )

        try:
            # Call the LLM in JSON mode
            json_response = self.llm.call(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                json_mode=True,
                temperature=0.1
            )

            # Parse the JSON string
            data = json.loads(json_response)
            files = data.get("files", {})

            if not files:
                self.log_failure(context, "LLM returned an empty files map.")
                raise ValueError("No files generated by LLM.")

            # Populate context terraform code
            context.terraform_code = files

            self.log_success(
                context, 
                f"Terraform compilation complete. Generated {len(files)} files: {', '.join(files.keys())}."
            )
            return context

        except Exception as e:
            self.log_failure(context, str(e))
            raise e
